### ISSUE TITLE
Colors not the same

### ISSUE THREAD

**Issue by EruditeBoen** [dracula/solidworks#4]
Im not sure if I didnt follow the steps correctly (I went over them 8 or 9 times), but instead of this:

![screenshot](https://github.com/dracula/solidworks/assets/27446292/346413f6-f2c5-42c7-b1a3-6a7ea98267b7)

I get this:

![Screenshot 2023-09-26 103959](https://github.com/dracula/solidworks/assets/27446292/09ba2b15-cc5a-4cc0-a6fa-23ef35e92498)

I am using solidworks 2023

can you tell which version of solidworks you are using?

**Comment by eleanor-clifford** [comment]
Hi @EruditeBoen, I tested this with solidworks 2018 and 2020 back when I made it (I don't use solidworks anymore), it's possible it just doesn't work in the new versions. The colors that get modified were originally in swStyleBlueu.dll, if you want you could try looking in it to see if they're still there.

Could be easy to make it work with the new version, could be hard, I don't know. You might find [my original blog post](https://tim.clifford.lol/blog/0001-dracula-for-solidworks/) on this theme somewhat useful if you want to give that a go.

**Comment by EruditeBoen** [comment]
It worked!

The problem was I did not have access to write to the dll so the override_background.sh was not running.

So I had to run sudo vim path-to-swStyleBlueu.dll. After that I had write access and was able to run override_background.sh

![Screenshot 2023-10-02 095852](https://github.com/dracula/solidworks/assets/27446292/9fc406ce-7f0a-4122-b3b7-6d7002694a32)

**Comment by eleanor-clifford** [comment]
Fantastic!
